import { WebsiteScanResult } from '../types/privacy';

export function downloadPrivacyReport(scan: WebsiteScanResult) {
  const content = `================================================================
                    PRIVACY GATE AUDIT REPORT
================================================================
Target Domain:         ${scan.domain}
Audit Timestamp:       ${scan.scannedAt}
Privacy Score:         ${scan.score} / 100
Risk Profile:          ${scan.score >= 80 ? 'LOW RISK' : scan.score >= 60 ? 'MODERATE RISK' : 'HIGH PRIVACY THREAT'}

----------------------------------------------------------------
SUMMARY METRICS
----------------------------------------------------------------
• Third-Party Domains:    ${scan.thirdPartyDomainsCount}
• Detected Trackers:      ${scan.trackerCount}
• Stored Cookies:         ${scan.cookiesCount}
• Fingerprinting Signal:  ${scan.fingerprintingDetected ? 'DETECTED (Canvas/WebGL)' : 'None'}
• Sensitive Data Leaks:   ${scan.sensitiveAlertsCount} alerts

----------------------------------------------------------------
DETECTED TRACKER DOMAINS
----------------------------------------------------------------
${scan.detectedTrackers.map(t => `  [!] ${t}`).join('\n')}

----------------------------------------------------------------
RECOMMENDED SECURITY ACTIONS
----------------------------------------------------------------
${scan.recommendations.map(r => `  [✓] ${r}`).join('\n')}

================================================================
Generated by Privacy Gate Zero-Trust Browser Firewall Prototype
Local-First Security Engine — Your Browser. Your Data. Your Visibility.
================================================================`;

  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `privacy-gate-report-${scan.domain}.txt`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
